import express  from "express";
import { authController } from "../controllers/index.js";
import protectRoute from "../Middlewares/protectRoute.js";
const router = express.Router();
router.post('/login',authController.login);
router.post('/register',authController.register);
router.get('/logout',authController.logout);
router.get('/me',protectRoute('admin'),authController.getMe);
router.post('/sendverifyotp',protectRoute('admin'),authController.sendVerifyOtp);
router.post('/verifyotp',protectRoute('admin'),authController.verifyOtp);
export default router;